"""initial

Revision ID: 480bb51ec296
Revises: 
Create Date: 2026-05-26 11:59:27.947114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '480bb51ec296'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owasp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity_weight', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='scanstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owasp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mitre_atlas_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failure_mode', sa.Enum('COMPLIED', 'PARTIAL', 'PII_LEAKED', 'HALLUCINATED_REFUSAL', 'REFUSED', 'FALSE_POSITIVE', name='failuremode'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('payload_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_scan_id'), 'finding', ['scan_id'], unique=False)
    op.create_table('scanevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanevent_scan_id'), 'scanevent', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanevent_scan_id'), table_name='scanevent')
    op.drop_table('scanevent')
    op.drop_index(op.f('ix_finding_scan_id'), table_name='finding')
    op.drop_table('finding')
    op.drop_table('scan')
    op.drop_table('plugin')
    # ### end Alembic commands ###
